### ISSUE TITLE
Inexact error when compositing samples

### ISSUE THREAD

**Issue by fnaghetini** [JuliaEarth/DrillHoles.jl#18] opened 2022-01-22 22:06 UTC
Hi there!

The `composite` function throws an **InexactError** when compositing some specific samples:

```julia
using DrillHoles

# raw tables
collar = Collar(file="collar.csv", holeid=:HOLEID, x=:X, y=:Y, z=:Z)
survey = Survey(file="survey.csv", holeid=:HOLEID, at=:AT, azm=:AZM, dip=:DIP)
assay = Interval(file="assay.csv", holeid=:HOLEID, from=:FROM, to=:TO)
litho = Interval(file="lithology.csv", holeid=:HOLEID, from=:FROM, to=:TO)

# desurveying
dh = drillhole(collar, survey, [assay, litho])

# compositing
composites = composite(dh, interval=5.0, mode=:nodiscard)

println(composites.table)
```

```julia
ERROR: LoadError: InexactError: Int64(5.015151515151516)
Stacktrace:
 [1] Int64
   @ .\float.jl:812 [inlined]
 [2] convert
   @ .\number.jl:7 [inlined]
 [3] setindex!(A::Vector{Int64}, x::Float64, i1::Int64)
   @ Base .\array.jl:903
 [4] insert_single_entry!(df::DataFrames.DataFrame, v::Float64, row_ind::Int64, col_ind::Symbol)
   @ DataFrames C:\Users\franc\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:631
 [5] setindex!(df::DataFrames.DataFrame, v::Float64, row_ind::Int64, col_ind::Symbol)
   @ DataFrames C:\Users\franc\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:659
 [6] composite(dhf::DrillHoles.DrillHole; interval::Float64, zone::Nothing, mode::Symbol, mincomp::Float64, gap::Float64)
   @ DrillHoles C:\Users\franc\.julia\packages\DrillHoles\ITApF\src\compositing.jl:129
```

Check [this gist](https://gist.github.com/fnaghetini/53dc842dbb5469c9f92140d94a24a996) to access data and script or, alternatively, [download the zip](https://github.com/JuliaEarth/DrillHoles.jl/files/7919376/Composite_Issue.zip).

**Obs.:** I'm using the latest version of `DrillHoles.jl`.

**Comment by juliohm** [comment] 2022-01-22 22:10
Hey @fnaghetini ! Can you give a try with the #cleanup branch to see if the issue is present there as well? You can `add DrillHoles#cleanup` to get the version.

The latest release has some known issues, some of which are fixed in the cleanup branch. We still need to finish the trajectory calculation, but I think I will go ahead and merge the cleanup branch on the master branch so that others can contribute PRs.

**Comment by juliohm** [comment] 2022-01-22 22:13
I have merged the #cleanup branch onto the #master branch, so you can try `add DrillHoles#master` now instead.

**Comment by juliohm** [comment] 2022-01-22 22:20
Please check the new README in the master branch on GitHub. The API changed and is more general now. We just need to adjust the trajectory calculation in the desurvey function and finish the composite methods. Pull requests with improvements are more than welcome!

**Comment by fnaghetini** [comment] 2022-01-23 23:35
It worked! Is there some way to access the old `warns` table?

**Comment by juliohm** [comment] 2022-01-23 23:40
Not currently as the current version is doing some fixes to the table when
possible and we didn't implement warnings as an output. We need to fix the
trajectories first and then start adding features. Help is appreciated here
specially if you are actively using the package at work.

**Closed** 2023-11-08 16:24 UTC
Labels: bug
